---
- name: Create Linux Report
  hosts: Linux
  vars:
    detailedreport: 'True'   # Define the variable here

  tasks:
    - name: Scan Systems for detailed report
      ansible.builtin.include_role:
        name: shadowman_scan_systems
      when: detailedreport == 'True'

    - name: Build the report
      ansible.builtin.include_role:
        name: build_report_linux
      delegate_to: 172.25.225.97
      run_once: true
