- name: Create Linux Report
  hosts: Linux
  become: true
  vars:
    detailedreport: true

  tasks:

    - name: Get latest 15 DNF update/install history IDs
      shell: |
        dnf history | awk '/Install|Update/ { print $1 }' | head -15
      register: patch_ids_raw
      changed_when: false

    - name: Get details of the last 15 patches
      shell: |
        dnf history info {{ item }}
      loop: "{{ patch_ids_raw.stdout_lines }}"
      register: patch_details
      changed_when: false

    - name: Concatenate all patch details into one string for report
      set_fact:
        last_patch_info: "{{ patch_details.results | map(attribute='stdout') | join('\n\n---\n\n') }}"

    - name: Get last reboot time
      shell: who -b
      register: reboot_time_raw
      changed_when: false

    - name: Parse last reboot time from 'who -b' output
      set_fact:
        last_reboot_time: "{{ reboot_time_raw.stdout.split('system boot')[1] | trim }}"

    - name: Save patch info to file for local inspection
      copy:
        content: |
          Last Reboot Time: {{ last_reboot_time }}

          Last 15 Patch Details:

          {{ last_patch_info }}
        dest: "/tmp/last_15_patch_info.txt"
        mode: '0644'

    - name: Set combined last patch and reboot info fact
      set_fact:
        last_patch_info: |
          Last Reboot Time: {{ last_reboot_time }}

          {{ last_patch_info }}

    - name: Scan Systems for detailed report
      include_role:
        name: shadowman_scan_systems
      when: detailedreport

# Run once to build report on the web server host
- name: Build the report using all hosts' data
  hosts: Linux
  run_once: true
  gather_facts: false
  become: true

  tasks:
    - name: Build the report
      include_role:
        name: build_report_linux
