- name: Create Linux Report
  hosts: Linux
  vars:
    detailedreport: 'True'

  tasks:
    - name: Scan Systems for detailed report
      include_role:
        name: shadowman_scan_systems
      when: detailedreport == 'True'

- name: Build the report on report server
  hosts: 172.25.225.97
  run_once: true

  tasks:
    - name: Build the report
      include_role:
        name: build_report_linux
