- name: Create Linux Report
  hosts: Linux
  become: true
  vars:
    detailedreport: true

  tasks:
    - name: Get available security patches using dnf
      shell: dnf updateinfo list security
      register: security_patches
      changed_when: false
      failed_when: false

    - name: Set security patches fact
      set_fact:
        security_patch_info: |
          Security Updates Available:
          {% if security_patches.stdout_lines %}
          {% for line in security_patches.stdout_lines %}
          - {{ line }}
          {% endfor %}
          {% else %}
          - No security patches available.
          {% endif %}

    - name: Get system date
      shell: date
      register: system_date
      changed_when: false

    - name: Get last 15 installed packages (names only)
      shell: "rpm -qa --last | head -15 | awk '{print $1}'"
      register: last_15_installed
      changed_when: false

    - name: Get last reboot time
      shell: who -b
      register: reboot_time_raw
      changed_when: false

    - name: Parse last reboot time from 'who -b' output
      set_fact:
        last_reboot_time: "{{ reboot_time_raw.stdout.split('system boot')[1] | trim }}"

    - name: Set combined last patch and reboot info fact
      set_fact:
        last_patch_info: |
          System Date: {{ system_date.stdout }}
          Last Reboot Time: {{ last_reboot_time }}

          Last 15 Installed Packages:
          {% for pkg in last_15_installed.stdout_lines %}
          - {{ pkg }}
          {% endfor %}

    - name: Save patch info to file for local inspection
      copy:
        content: "{{ last_patch_info }}"
        dest: "/tmp/last_15_patch_info.txt"
        mode: '0644'

    - name: Scan Systems for detailed report
      include_role:
        name: shadowman_scan_systems
      when: detailedreport

# Run once to build report on the web server host
- name: Build the report using all hosts' data
  hosts: Linux
  run_once: true
  gather_facts: false
  become: true

  tasks:
    - name: Build the report
      include_role:
        name: build_report_linux
