---
- name: Create Linux Report with Security Patches Only
  hosts: Linux
  become: true
  gather_facts: true
  vars:
    detailedreport: true

  tasks:
    - name: Refresh yum metadata cache
      command: yum makecache
      changed_when: false

    - name: Get list of applicable security patches
      command: yum updateinfo list security
      register: security_patches
      changed_when: false

    - name: Set security patch info fact
      set_fact:
        patch_info: |
          Applicable Security Patches:
          {% if security_patches.stdout_lines %}
          {% for patch in security_patches.stdout_lines %}
          - {{ patch }}
          {% endfor %}
          {% else %}
          - No applicable security patches found.
          {% endif %}

    - name: Save patch info to file for local inspection
      copy:
        content: "{{ patch_info }}"
        dest: "/tmp/security_patch_info.txt"
        mode: '0644'

    - name: Scan Systems for detailed report
      include_role:
        name: shadowman_scan_systems
      when: detailedreport

- name: Aggregate patch info from all hosts
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Aggregate patch info facts from Linux hosts
      set_fact:
        all_patch_info: "{{ groups['Linux'] | map('extract', hostvars, 'patch_info') | list }}"

    - name: Debug aggregated patch info
      debug:
        var: all_patch_info

- name: Build the report using aggregated data
  hosts: Linux
  gather_facts: false
  tasks:
    - name: Build the report
      include_role:
        name: build_report_linux
      vars:
        aggregated_patch_info: "{{ all_patch_info }}"
