- name: Scan Linux hosts for security patches
  hosts: Linux
  become: true
  gather_facts: true
  vars:
    detailedreport: true

  tasks:
    - name: Run scan role to gather patch info
      include_role:
        name: shadowman_scan_systems

- name: Build combined report on localhost
  hosts: localhost
  gather_facts: false
  become: false
  run_once: true

  vars:
    # Aggregate patch info facts from all Linux hosts
    aggregated_patch_info: "{{ groups['Linux'] | map('extract', hostvars, 'patch_info') | list }}"

  tasks:
    - name: Build combined report using aggregated patch info
      include_role:
        name: build_report_linux
      vars:
        all_patch_info: "{{ aggregated_patch_info }}"
