- name: Create Linux Report with Security Patches Only
  hosts: Linux
  become: true
  gather_facts: true
  vars:
    detailedreport: true

  tasks:
    - name: Get list of applicable security patches
      shell: yum updateinfo list security
      register: security_patches
      changed_when: false

    - name: Set security patch info fact
      set_fact:
        patch_info: |
          Applicable Security Patches:
          {% if security_patches.stdout_lines %}
          {% for patch in security_patches.stdout_lines %}
          - {{ patch }}
          {% endfor %}
          {% else %}
          - No applicable security patches found.
          {% endif %}

    - name: Save patch info to file for local inspection
      copy:
        content: "{{ patch_info }}"
        dest: "/tmp/security_patch_info.txt"
        mode: '0644'

    - name: Scan Systems for detailed report
      include_role:
        name: shadowman_scan_systems
      when: detailedreport

# Run once to build report using data from all hosts
- name: Build the report using all hosts' data
  hosts: Linux
  run_once: true
  gather_facts: true
  become: true

  tasks:
    - name: Build the report
      include_role:
        name: build_report_linux
